version: '3'
services:
  app-symphony:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - '8084:80'
    depends_on:
      - mysql
    restart: always
  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=dbapp
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin   
    platform: linux/arm64 
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    ports:
      - "8085:80"
    restart: always